filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: 'unix:///var/run/docker.sock'

  - decode_json_fields:
      fields: ['message']
      target: 'json'
      overwrite_keys: true

output.elasticsearch:
  # if container running same network with ELK => use elasticsearch container name
  # else use the ip of elasticsearch
  hosts: ['host.docker.internal:9200'] # ['elasticsearch:9200']
  indices:
    - index: 'filebeat-%{[agent.version]}-%{+yyyy.MM.dd}'

logging.json: true
logging.metrics.enabled: false
